### ISSUE TITLE
[STU-146] Editing an existing export gives error when a new field has been added to its Entry Type

### ISSUE THREAD

**Issue by HannahDeWachter** [studioespresso/craft-exporter#11]
I have set up an export for Entries. When adding an new field to this Section/Entry Type, I wanted to edit this export to also include this new field. When trying to do this I get following error:

![image](https://uploads.linear.app/0aa2dff2-16ce-49c1-8b10-cf8b7d9d79ad/d68f43c0-9593-494a-a6e1-d22096b81079/671a8b67-5597-4bd2-b3c9-adf5a33529a9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzBhYTJkZmYyLTE2Y2UtNDljMS04YjEwLWNmOGI3ZDlkNzlhZC9kNjhmNDNjMC05NTkzLTQ5NGEtYTZlMS1kMjIwOTZiODEwNzkvNjcxYThiNjctNTU5Ny00YmQyLWIzYzktYWRmNWEzMzUyOWE5IiwiaWF0IjoxNzEyOTI2MDI1LCJleHAiOjE3MTMwMTI0MjV9.xnyC_KZHgzSBaFw23JVveV4l0529STT-KQ03fcKo-tg)

<sub>From [SyncLinear.com](https://synclinear.com) | [STU-146](https://linear.app/studio-espresso/issue/STU-146/editing-an-existing-export-gives-error-when-a-new-field-has-been-added)</sub>

**Comment by janhenckens** [comment]
Fixed in 4.1.0
