### ISSUE TITLE
"Unknown "d" function." Error when trying to add a new export

### ISSUE THREAD

**Issue by okadots** [studioespresso/craft-exporter#14]
Installed the latest version on Craft 4.8.9.
Installation seems to have gone ok, but when I navigate to "New Export", I get the error below. 
![image](https://github.com/studioespresso/craft-exporter/assets/313852/f9a5b589-6811-4961-94e7-bfaf14b716b1)

**Comment by janhenckens** [comment]
Hey @okadots, thanks for reporting that - and sorry about the error.

Should be fixed in the latest update (4.1.1), could you install that and try again?

**Comment by okadots** [comment]
Thanks for the fast turn around @janhenckens ! Looks like we are in good shape now
